# Build the upstream Electron application from a pinned release source tag.
# Source0 is the surrounding rpm-packages repository generated by rpkg.

%global debug_package %{nil}
%global _build_id_links none
%global upstream_version 1.10.3
%global upstream_source_sha256 f6e63bb96f9333e0c92f27fbca695a6dfbae06439f3d34da8a0efcb8323cd5c4
%global proxy_version 1.8.0
%global proxy_license_sha256 8b80747b4460ced250cda25905c02f2b5d6e64d1c05aa8d7ba727abd726c065e
%ifarch x86_64
%global electron_arch x64
%endif
%ifarch aarch64
%global electron_arch arm64
%endif

Name:           freelens-bundled
Version:        %{upstream_version}
Release:        8%{?dist}
Summary:        Free IDE for Kubernetes with the upstream Electron runtime
# FreeLens and freelens-k8s-proxy are MIT; kubectl and Helm are Apache-2.0.
# The generated third-party notice and Electron/Chromium notices installed
# below preserve the licenses of bundled runtime dependencies.
License:        MIT AND Apache-2.0
URL:            https://freelens.app/
# rpkg expands Source0 from the committed repository. Source1 is the pinned
# upstream GitHub release tag; the Electron application is built inside Mock.
Source0:        {{{ git_repo_pack }}}
Source1:        https://github.com/freelensapp/freelens/archive/refs/tags/v%{upstream_version}.tar.gz#/freelens-%{upstream_version}.tar.gz
Source2:        https://raw.githubusercontent.com/freelensapp/freelens-k8s-proxy/v%{proxy_version}/LICENSE#/LICENSE.freelens-k8s-proxy

# Do not derive ELF dependencies from the bundled Chromium/Electron libraries:
# they would expose private bundled libraries as RPM capabilities and make the
# package depend on implementation details. Keep the runtime contract explicit.
AutoReqProv:    no
ExclusiveArch:  x86_64 aarch64
BuildRequires:  cpio
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
# Fedora's generic nodejs capability currently resolves to nodejs22; Freelens
# declares Node >=24, so request the versioned Fedora packages explicitly.
BuildRequires:  nodejs24
BuildRequires:  nodejs24-npm
BuildRequires:  python3
BuildRequires:  rpm
Requires:       libasound.so.2()(64bit)
Requires:       at-spi2-core
Requires:       gtk3
Requires:       libXss.so.1()(64bit)
Requires:       libnotify.so.4()(64bit)
Requires:       nss
Requires:       libvulkan.so.1()(64bit)
Requires:       xdg-utils
# Replace the original GitHub RPM and this repository's pre-variant package
# without replacing a newer upstream version during a downgrade attempt.
Provides:       freelens = %{version}-%{release}
Obsoletes:      freelens < %{version}-%{release}
Conflicts:      freelens-native

%description
Freelens is a free and open-source Kubernetes IDE. This compatibility variant
uses the upstream Electron runtime and bundles compatible kubectl, Helm, and
Freelens Kubernetes proxy binaries.

%prep
printf '%s  %s\n' '%{upstream_source_sha256}' '%{SOURCE1}' | sha256sum -c -
printf '%s  %s\n' '%{proxy_license_sha256}' '%{SOURCE2}' | sha256sum -c -
%setup -q -n rpm-packages -a 1

%build
cd freelens-%{upstream_version}
# Mock builds as the unprivileged mockbuild user. Install Corepack locally
# rather than into npm's root-owned global prefix, then expose its pnpm shim.
# TODO: replace this temporary bootstrap with a Corepack RPM built in this COPR
# repository and add it to BuildRequires.
npm install --ignore-scripts --no-audit --no-fund --prefix .build-tools corepack@0.34.0
mkdir -p .build-tools/bin
node .build-tools/node_modules/corepack/dist/corepack.js enable --install-directory "$PWD/.build-tools/bin"
export PATH="$PWD/.build-tools/bin:$PATH"
pnpm install --frozen-lockfile
pnpm build:di
pnpm build
pnpm build:app dir --%{electron_arch}
test -x freelens/dist/linux-unpacked/freelens

%install
install -d %{buildroot}%{_bindir} %{buildroot}%{_libdir}
cp -a freelens-%{upstream_version}/freelens/dist/linux-unpacked \
    %{buildroot}%{_libdir}/freelens

# This runtime-loaded native module is prebuilt by upstream. Strip its debug
# sections without changing executable code or its bundled ABI.
%{__strip} --strip-unneeded \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/node-pty/bin/linux-%{electron_arch}-*/node-pty.node \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/node-pty/prebuilds/linux-%{electron_arch}/pty.node

# Electron bundles the Vulkan loader, but Fedora supplies the compatible
# system loader through the explicit libvulkan.so.1 dependency above.
rm -f %{buildroot}%{_libdir}/freelens/libvulkan.so.1

# electron-builder leaves prebuilt extract-zip add-ons for every platform in
# app.asar.unpacked. Keep only the glibc build for the target architecture.
extract_zip_dir=%{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/@electron-internal/extract-zip
find "$extract_zip_dir" -type f -name '*.node' \
    ! -name 'index.linux-%{electron_arch}-gnu.node' -delete

# Build-time metadata and Windows-only headers cannot be used by the Linux
# runtime and should not be carried in the installed application.
rm -f \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/jszip/.codeclimate.yml \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/jszip/.editorconfig \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/jszip/.eslintrc.js \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/jszip/.jekyll-metadata \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/node-pty/src/win/conpty.h \
    %{buildroot}%{_libdir}/freelens/resources/app.asar.unpacked/node_modules/node-pty/src/win/path_util.h

# Use a relative target so RPM can relocate the package without an
# absolute-symlink diagnostic.
ln -s ../%{_lib}/freelens/freelens %{buildroot}%{_bindir}/freelens
install -Dm0644 freelens-bundled/freelens.1 %{buildroot}%{_mandir}/man1/freelens.1
install -Dm0644 freelens-bundled/freelens.desktop \
    %{buildroot}%{_datadir}/applications/freelens.desktop
install -Dm0644 freelens-%{upstream_version}/freelens/build/metainfo.xml \
    %{buildroot}%{_datadir}/metainfo/app.freelens.Freelens.metainfo.xml
install -Dm0644 freelens-%{upstream_version}/LICENSE \
    %{buildroot}%{_licensedir}/%{name}/LICENSE.freelens
install -Dm0644 freelens-%{upstream_version}/freelens/static/build/license.txt \
    %{buildroot}%{_licensedir}/%{name}/THIRD-PARTY-LICENSES.txt
install -Dm0644 %{SOURCE2} \
    %{buildroot}%{_licensedir}/%{name}/LICENSE.freelens-k8s-proxy
for icon in freelens-%{upstream_version}/freelens/build/icons/*.png; do
    size="$(basename "$icon" .png)"
    install -Dm0644 "$icon" \
        %{buildroot}%{_datadir}/icons/hicolor/${size}/apps/freelens.png
done

# Keep license files marked as licenses without listing them twice through the
# recursively installed application directory.
(
    find %{buildroot}%{_libdir}/freelens -mindepth 1 -type d \
        -printf '%%%%dir %{_libdir}/freelens/%%P\n'
    find %{buildroot}%{_libdir}/freelens -mindepth 1 \( -type f -o -type l \) \
        ! -path '%{buildroot}%{_libdir}/freelens/LICENSE.electron.txt' \
        ! -path '%{buildroot}%{_libdir}/freelens/LICENSES.chromium.html' \
        -printf '%{_libdir}/freelens/%%P\n'
) > %{_builddir}/freelens.files

%check
test -x %{buildroot}%{_libdir}/freelens/freelens
test -f %{buildroot}%{_datadir}/applications/freelens.desktop
test -f %{buildroot}%{_datadir}/metainfo/app.freelens.Freelens.metainfo.xml
test -s %{buildroot}%{_licensedir}/%{name}/LICENSE.freelens
test -s %{buildroot}%{_licensedir}/%{name}/THIRD-PARTY-LICENSES.txt
test -s %{buildroot}%{_licensedir}/%{name}/LICENSE.freelens-k8s-proxy

%files -f %{_builddir}/freelens.files
%dir %{_libdir}/freelens
%license %{_libdir}/freelens/LICENSE.electron.txt
%license %{_libdir}/freelens/LICENSES.chromium.html
%license %{_licensedir}/%{name}/LICENSE.freelens
%license %{_licensedir}/%{name}/THIRD-PARTY-LICENSES.txt
%license %{_licensedir}/%{name}/LICENSE.freelens-k8s-proxy
%doc freelens-%{upstream_version}/README.md
%{_bindir}/freelens
%{_mandir}/man1/freelens.1*
%{_datadir}/applications/freelens.desktop
%{_datadir}/icons/hicolor/*/apps/freelens.png
%{_datadir}/metainfo/app.freelens.Freelens.metainfo.xml

%changelog
* Thu Sep 24 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-8
- Build Electron and retain native modules for the target architecture.

* Tue Sep 22 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-7
- Install the FreeLens, generated dependency, and proxy license texts.
- Account for bundled Apache-2.0 helper binaries in the package license.

* Fri Sep 04 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-6
- Rename the compatibility package to freelens-bundled.
- Replace older unqualified freelens packages and conflict with freelens-native.

* Fri Sep 04 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-5
- Use Fedora's Vulkan loader and discard non-target native add-ons.

* Fri Sep 04 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-4
- Add rpmlint-clean package metadata, documentation, and man page.
- Remove non-runtime Node module source and metadata from the installed app.

* Fri Sep 04 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-3
- Fix the /usr/bin/freelens launcher to use a relative symlink.

* Fri Sep 04 2026 Anatolii Vorona <vorona.tolik@gmail.com> - 1.10.3-2
- Initial downstream RPM repackage of the verified upstream binary release.
