.TH FREELENS 1
.SH NAME
freelens \- free Kubernetes IDE
.SH SYNOPSIS
.B freelens
.RI [ options ]
.SH DESCRIPTION
.B Freelens
is a graphical integrated development environment for managing Kubernetes
clusters.
.SH OPTIONS
Freelens accepts the standard Electron command-line options.  For application
usage, see the in-application help and https://freelens.app/.
.SH SEE ALSO
.BR kubectl (1),
.BR helm (1)
